# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-29 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20180329_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='content1',
            new_name='content',
        ),
    ]
